take_calibrated_picture: take_calibrated_picture.cc
	g++ -o take_calibrated_picture `pkg-config --cflags opencv` `pkg-config --libs opencv` take_calibrated_picture.cc

clean:
	rm take_calibrated_picture
